#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue Mar 10 23:31:48 EDT 2026
maven-metadata-ApacheSnapshot.xml.error=
maven-metadata-ApacheSnapshot.xml.lastUpdated=1773199908058
